/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elbasurero;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author jukama999
 */
public class Inventario extends javax.swing.JFrame {
    
   
   DefaultTableModel modelo;
   ArrayList<Productos> listProductos = new ArrayList<>();
   ArrayList<Productos> listProductosTodos = new ArrayList<>();
   ArrayList<Mesa> listMesas = new ArrayList<>();
   Conexion conec = new Conexion();
   Connection conectar ;
   
   LocalDateTime fecha_actual = LocalDateTime.now();
   
   String fecha;
   int mesasIndex=0;
   int select;
   int product;
   int canti;
   
    
    public Inventario() {
        initComponents();
//        llenarMesas();
        llenarProductos();
        modelo=(DefaultTableModel) jTable1.getModel();
        modelo=new DefaultTableModel();
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio Unitario");
        modelo.addColumn("Precio Total");
      
       fecha = fecha_actual.toString();
        jLabel1.setText(fecha);
        
        
        this.jTable1.setModel(modelo); 
       
        llenarMesas();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btneliminarpedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        lblprecio = new javax.swing.JLabel();
        lblprecio1 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jcbmesas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcbproductos = new javax.swing.JComboBox<>();
        txttotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setMinimumSize(new java.awt.Dimension(100, 100));
        jTable1.setPreferredSize(new java.awt.Dimension(500, 300));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 630, 150));

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/insert_object.png"))); // NOI18N
        btnagregar.setBorder(null);
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 120, 120));

        btneliminarpedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/list_remove.png"))); // NOI18N
        btneliminarpedido.setBorder(null);
        btneliminarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarpedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminarpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 248, 120, 120));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Arial Nova", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Productos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 120, 40));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Arial Nova", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 110, -1));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_all.png"))); // NOI18N
        btnguardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnguardar.setBorderPainted(false);
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnguardarMouseClicked(evt);
            }
        });
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 120, 120));

        lblprecio.setBackground(new java.awt.Color(153, 153, 153));
        lblprecio.setFont(new java.awt.Font("Arial Nova", 1, 24)); // NOI18N
        lblprecio.setForeground(new java.awt.Color(153, 153, 153));
        lblprecio.setText("0.0");
        jPanel1.add(lblprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 100, 30));

        lblprecio1.setBackground(new java.awt.Color(153, 153, 153));
        lblprecio1.setFont(new java.awt.Font("Arial Nova", 1, 24)); // NOI18N
        lblprecio1.setForeground(new java.awt.Color(153, 153, 153));
        lblprecio1.setText("Precio :");
        jPanel1.add(lblprecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jSpinner2.setValue(1);
        jPanel1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 50, 30));

        jcbmesas.setFont(new java.awt.Font("Arial Nova", 0, 18)); // NOI18N
        jcbmesas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbmesasItemStateChanged(evt);
            }
        });
        jcbmesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbmesasMouseClicked(evt);
            }
        });
        jcbmesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbmesasActionPerformed(evt);
            }
        });
        jPanel1.add(jcbmesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 294, 120, 30));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Arial Nova", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Mesas:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, 30));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Arial Nova", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Total:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 610, 90, 40));

        lbltotal.setBackground(new java.awt.Color(204, 204, 204));
        lbltotal.setFont(new java.awt.Font("Arial Nova", 1, 24)); // NOI18N
        lbltotal.setForeground(new java.awt.Color(102, 102, 102));
        lbltotal.setText("0.0");
        jPanel1.add(lbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 180, 50));

        jLabel1.setFont(new java.awt.Font("Arial Nova", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("AA-MM-DD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 220, 30));

        jcbproductos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcbproductos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbproductosItemStateChanged(evt);
            }
        });
        jcbproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbproductosMouseClicked(evt);
            }
        });
        jcbproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbproductosActionPerformed(evt);
            }
        });
        jPanel1.add(jcbproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 220, -1));

        txttotal.setBackground(new java.awt.Color(204, 204, 204));
        txttotal.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        txttotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Simple Starter Template v0.1 (Community).png"))); // NOI18N
        txttotal.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 0, 1150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    
    
    public int sumar(){
        
        int contar=jTable1.getRowCount();
        int suma=0;
        for(int i=0;i<contar;i++){
            suma=suma+Integer.parseInt(jTable1.getValueAt(i,3).toString());
    
      }
        return suma;
    }
    
    
    private void Populate(String producto ){
        String[] rowData={producto};
        modelo.addRow(rowData);
        
        
    }
    
    private void llenarProductos(){
        ModeloProductos modProductos = new ModeloProductos();
       try {
           listProductosTodos = modProductos.getProductos();
       } catch (SQLException ex) {
           Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
       }
       
       jcbproductos.removeAll();
       
       for(int i=0; i<listProductosTodos.size();i++){
           jcbproductos.addItem(listProductosTodos.get(i).getProductos());
       }
    }
    
    private void llenarMesas(){
        ModeloMesas modelMesas = new ModeloMesas();

    try {
           listMesas = modelMesas.getMesas();
       } catch (SQLException ex) {
           Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
       }
       
       jcbmesas.removeAll();
       
       for(int i=0; i<listMesas.size();i++){
           listMesas.get(i).listProductos = new ArrayList<>();
           jcbmesas.addItem(listMesas.get(i).getName());
       }
    }
    
    private void btneliminarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarpedidoActionPerformed
       
       int rowIndex = jTable1.getSelectedRow();
       if(rowIndex == -1){
           return;
       }
       
       
       modelo.removeRow(rowIndex);
       listProductos.remove(rowIndex);
       
       refrescarTabla();
    }//GEN-LAST:event_btneliminarpedidoActionPerformed

    
    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        Populate(jcbproductos.getSelectedItem().toString());
        try{

        
        product = jcbproductos.getSelectedIndex();
        select = jcbmesas.getSelectedIndex();
        canti = (int) jSpinner2.getValue();
        
       
        
        Productos productoSeleccionado = listProductosTodos.get(product);
        Productos nuevoproducto = new Productos();
        nuevoproducto.setProductos(productoSeleccionado.getProductos());
        nuevoproducto.setPrecio(productoSeleccionado.getPrecio());
        nuevoproducto.setId_inventario(productoSeleccionado.getId_inventario());
        nuevoproducto.setCantidad(canti);
        nuevoproducto.setPrecio_total();
         listProductos.add(nuevoproducto);
         
        
        
         

       
        refrescarTabla();
     
         
     }catch(Exception e){
         
         JOptionPane.showMessageDialog(this,"Error");
     }
  
    }//GEN-LAST:event_btnagregarActionPerformed
    
              
    public void refrescarTabla(){
     
          while(modelo.getRowCount()>0){
              modelo.removeRow(0);
          }
      
        for(Productos producto :  listProductos){
            Object p[]=new Object[4];
            p[0]=producto.getProductos();
            p[1]=producto.getCantidad();
            p[2]=producto.getPrecio();
            p[3]=producto.getPrecio_total();
       
                    
            modelo.addRow(p);
             
         }
          
         this.jTable1.setModel(modelo);
       
    }
    
    
    private void jcbproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbproductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbproductosActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       try {
           
           Productos id = new Productos();
           
            product = jcbproductos.getSelectedIndex();
            select = jcbmesas.getSelectedIndex();
             canti = (int) jSpinner2.getValue();
             
           
           int selec = listMesas.get(select).getId();
           
           Connection con = Conexion.getConexion();
           Statement stmt;
           ResultSet rs;
           PreparedStatement ps = null;
           PreparedStatement ps1;
           PreparedStatement ps2;
           
           stmt = con.createStatement();
           
           
           ps = con.prepareStatement("INSERT INTO factura (Fecha ,Id_Mesa)VALUES(?,?)");
           ps.setString(1,fecha);
           ps.setInt(2,selec);
           ps.executeUpdate();
           
           
            rs = stmt.executeQuery("SELECT MAX(Id_Factura) AS Id_Factura FROM factura");
            if(rs.next()){
            id.setId_factura(rs.getInt(1)+1);
            System.out.println(id.getId_factura());
            }
           
           for(int i=0;i<modelo.getRowCount();i++){
           
           
//            
          int valor = listProductos.get(i).getId_inventario();
          int cant = listProductos.get(i).getCantidad();
          
          ps1 = con.prepareStatement("INSERT INTO item (Id_Inventario,Id_Factura,Cantidad)VALUES(?,?,?)");
                
           ps1.setInt(1,valor);
           ps1.setInt(2,id.getId_factura());
           ps1.setInt(3,cant);
           
            int resultado = ps.executeUpdate();
           int result = ps1.executeUpdate();
           
            if (resultado > 0){
               JOptionPane.showMessageDialog(null,"Productos Guardados");
           }
           if(result > 0){
               JOptionPane.showMessageDialog(null,"Productos Guardados");
           }
           }
           
           modelo.getDataVector().removeAllElements();
           modelo.fireTableDataChanged();
           
           listMesas.removeAll(listMesas);
           
         
           

         
           


       } catch (SQLException ex) {
           Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
       }
      
    }//GEN-LAST:event_btnguardarActionPerformed

    private void jcbproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbproductosMouseClicked
       
           
    }//GEN-LAST:event_jcbproductosMouseClicked

    private void jcbproductosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbproductosItemStateChanged
       product = jcbproductos.getSelectedIndex();
       
       
          String precio = Integer.toString(listProductosTodos.get(product).getPrecio());  
          String id = Integer.toString(listProductosTodos.get(product).getId_inventario());
          
              lblprecio.setText(precio);
              
    }//GEN-LAST:event_jcbproductosItemStateChanged

    private void jcbmesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbmesasActionPerformed
     
    }//GEN-LAST:event_jcbmesasActionPerformed

    private void jcbmesasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbmesasItemStateChanged
               
        
          
         int index = jcbmesas.getSelectedIndex();

         System.err.println(listProductos);

         Mesa mesaPrevia = listMesas.get(mesasIndex);

         mesaPrevia.setListProductos(listProductos);
         Mesa mesaSeleccionada = listMesas.get(index);
         listProductos = mesaSeleccionada.getListProductos();
   
         mesasIndex = index;
         
      
         
         
        
  refrescarTabla();
         
         

         
         
//          
      
       
       
    }//GEN-LAST:event_jcbmesasItemStateChanged

    private void jcbmesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbmesasMouseClicked
       lbltotal.setText(Integer.toString(sumar()));
         
    }//GEN-LAST:event_jcbmesasMouseClicked

    private void btnguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseClicked
        
        
    }//GEN-LAST:event_btnguardarMouseClicked
    private void filter (String query){
         TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(modelo);
         jTable1.setRowSorter(tr);
         
         if(query == "None"){
             tr.setRowFilter(RowFilter.regexFilter(query));
         }else{
             jTable1.setRowSorter(tr);
         }
    }
   


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminarpedido;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbmesas;
    private javax.swing.JComboBox<String> jcbproductos;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lblprecio1;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
